package org.secuso.privacyfriendlybackup.worker.datakeys

const val DATA_OPENPGP_PROVIDER = "DATA_OPENPGP_PROVIDER"
const val DATA_CALLING_PACKAGE_NAME = "DATA_CALLING_PACKAGE_NAME"
const val DATA_ID = "DATA_ID"
const val DATA_JOB_ID = "DATA_JOB_ID"
const val DATA_ENCRYPT = "DATA_ENCRYPT"
const val DATA_KEY_ID = "DATA_KEY_ID"
const val DATA_SIGNING_KEY_ID = "DATA_SIGNING_KEY_ID"
const val DATA_PASSPHRASE = "DATA_PASSWPHRASE"
const val DATA_BACKUP_LOCATION = "DATA_BACKUP_LOCATION"
const val DATA_TIMESTAMP = "DATA_TIMESTAMP"